backend:
#  name: test-repo
  name: github
  repo: anand-simmy/nextjs-netlify-cms
  branch: main
  open_authoring: true
publish_mode: editorial_workflow

media_folder: public/img
public_folder: img


site_url: https://razorthinkcms.netlify.app
logo_url: https://www.razorthink.com/wp-content/uploads/2020/11/logo.png

i18n:
  structure: multiple_files
  locales: [en, de, fr]
collections:
  - name: "general" # Used in routes, e.g., /admin/collections/blog
    label: "General" # Used in the UI
    folder: "contents/general" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    i18n: true
    nested:
      depth: 100
    fields:
      - {  label: "Select Category", name: "primecat", widget: "select", options: [{ label: "Overview", value: "overview" },{ label: "Setup", value: "setup" },{ label: "Troubleshoot", value: "troubleshoot" }], i18n: true}
      - {  label: "Select Secondary Category", name: "seccat", widget: "select", options: [{ label: "Overview", value: "overview" },{ label: "Setup", value: "setup" },{ label: "Troubleshoot", value: "troubleshoot" }], i18n: true}
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Author", name: "author", widget: "string", required: false, i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false, i18n: duplicate }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false, i18n: true }
    path: '{{primecat}}/{{seccat}}/docs/{{title}}'

  - name: "pipelines"
    label: "Pipelines"
    folder: "contents/pipelines"
    create: true
    slug: "{{slug}}"
    nested:
      depth: 100
      summary: '{{title}}'
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "faq"
    label: "FAQ"
    folder: "contents/faq"
    create: true
    slug: "{{slug}}"
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }